"""This is a template for State Machine Modules

   A State Machine module is a python file that contains a  `loop` function.
   Similar to how an Arduino program operates, `loop` is called continuously:
   when the function terminates, it is called again.

   The `loop` function should continuously listens to messages generated by:
   - the path detector (concerning the path to follow),
   - the sign detector (concerning road signs detected, if any),
   - the remote command operator (concerning commands to start/stop driving,
     or do specific manoeuvers)
   - and the arduino controller of the physical car (concerning the current
     state; possible sensor readings, ...)

   and decide on how to drive the car correspondingly. See the description of
   the `loop` method below for more details.

   This simplistic State Machine responds to remote commands "GO", "STOP"
   and "TEST_COMM". In addition, it listens to path information from the
   Simplistic Path detector, and sends actuation commands that are
   compatible with the simulator.
"""


import logging
import time
from event import Event
from car import Car


# Setup up the state machine. The following code is called when the state
# machine is loaded for the first time.
logging.info('Simplistic StateMachine has been initialized')



def loop():

    event = Event.poll()
    if event is not None:

        if event.type == Event.PATH:

            tmp = event.val 
            command = tmp['command'] 
            if command == 'a' : 
                Car.send(0, 0, 2., 2.) 
            elif command == 'd' : 
                Car.send(0, 0, 2., -2.) 
            elif command == 'w' : 
                Car.send(0, 0, 2., 0.) 
            elif command == ' ' :
                Car.send(0, 0, 0., 0.)
            
        elif event.type == Event.SIGN:

            tmp = event.val
            if not tmp['sign'] == None : 
                logging.info(tmp['sign']) 
            sign = tmp['sign']
    
    
